import type { TimelineEventType } from '../types/activity'

const LUNCH_FIRST = 'Tushlik boshlanishi'
const LUNCH_SECOND = 'Tushlik tugashi'

export function timelineLabel(
  type: TimelineEventType,
  lunchIndex: number,
): string {
  if (type === 'door_in') return 'Ofisga kirish'
  if (type === 'door_out') return 'Ofisdan chiqish'
  if (type === 'pc_active') return 'Kompyuter faolligi boshlandi'
  if (type === 'idle_start') return 'Tushkunlik boshlandi'
  if (type === 'lunch') return lunchIndex === 0 ? LUNCH_FIRST : LUNCH_SECOND
  return type
}

export const UI = {
  brand: 'WorkPulse',
  brandTagline: 'Xodim faolligi monitoringi',
  appTitle: 'Faollik monitoringi',
  dashboard: 'Boshqaruv paneli',
  navActivity: 'Faollik',
  navEmployees: 'Xodimlar',
  navAnalytics: 'Analitika',
  navAttendance: 'Yo‘qlama',
  navAdmins: 'Administratorlar',
  navDepartments: 'Bo‘limlar',
  navRooms: 'Xonalar',
  navPositions: 'Lavozimlar',
  navComputers: 'Kompyuterlar',
  deptPageDesc: 'Bo‘limlar katalogi va kodlari',
  roomsPageDesc: 'Ofis xonalari',
  positionsPageDesc: 'Standart lavozim nomlari (xodim kartasida tanlash uchun)',
  computersPageDesc: 'MAC manzil, mashina tokeni va xodim/xonaga biriktirish',
  login: 'Tizimga kirish',
  loginSubtitle: 'Korxona hisobingiz bilan kiring',
  loginField: 'Email',
  password: 'Parol',
  signIn: 'Kirish',
  signOut: 'Chiqish',
  themeLight: 'Yorug‘',
  themeDark: 'Qorong‘u',
  themeLabel: 'Rejim',
  dateFilter: 'Sana oralig‘i',
  searchPlaceholder: 'Xodim yoki bo‘lim bo‘yicha qidirish',
  summary: 'Umumiy ko‘rsatkichlar',
  tableTitle: 'Kunlik faollik jadvali',
  detailTitle: 'Kunlik tafsilotlar',
  colEmployee: 'Xodim',
  colDate: 'Sana',
  colOfficeIn: 'Ofisga kirish',
  colRoomIn: 'Xonaga kirish (birinchi PC)',
  colActive: 'Faol vaqt',
  colIdle: 'Tushkunlik',
  colLunch: 'Tushlik',
  colOfficeOut: 'Ofisdan chiqish',
  colEfficiency: 'Samaradorlik',
  kpiTotal: 'Jami xodimlar',
  kpiActiveToday: 'Bugun faol',
  kpiAvgEff: 'O‘rtacha samaradorlik',
  kpiWorkHours: 'Jami ish vaqti',
  kpiIdle: 'Jami tushkunlik vaqti',
  totalActive: 'Jami faol vaqt',
  totalIdle: 'Jami tushkunlik',
  efficiencyScore: 'Samaradorlik',
  timelineTitle: 'Vaqt bo‘yicha voqealar',
  barTitle: 'Kun davomiyligi (segmentlar)',
  trendUp: 'o‘sish',
  trendDown: 'pasayish',
  noData: 'Ma’lumot yo‘q',
  close: 'Yopish',
  employeesPageTitle: 'Xodimlar ro‘yxati',
  employeesPageDesc: 'Jamoa a’zolari va o‘rtacha ko‘rsatkichlar',
  colDepartment: 'Bo‘lim',
  colPosition: 'Lavozim',
  colStatus: 'Holat',
  colRecords: 'Yozuvlar',
  colLastActivity: 'Oxirgi faollik',
  statusActive: 'Faol',
  statusAway: 'Yoq',
  statusOffline: 'Oflayn',
  analyticsTitle: 'Analitika',
  analyticsDesc:
    'Samaradorlik va jamoa dinamikasi (faqat bo‘limi biriktirilgan xodimlar hisobga olinadi)',
  unassignedDept: 'Bo‘limsiz',
  chartTrend: 'Kunlar bo‘yicha o‘rtacha samaradorlik',
  chartByEmployee: 'Xodimlar bo‘yicha',
  chartByDept: 'Bo‘limlar bo‘yicha',
  chartActiveIdle: 'Faol va tushkun vaqt (jami, daqiqa)',
  userMenu: 'Profil',
  notifications: 'Bildirishnomalar',
  collapseSidebar: 'Yig‘ish',
  expandSidebar: 'Kengaytirish',
  colNameDept: 'Nomi',
  colRoomName: 'Xona',
  colPositionName: 'Lavozim',
  colComputerName: 'Kompyuter',
  colCode: 'Kod',
  colDescription: 'Tavsif',
  colActions: 'Amallar',
  colMac: 'MAC',
  colLastSeen: 'Oxirgi aloqa',
  confirmDelete: 'O‘chirishni tasdiqlaysizmi?',
  add: 'Qo‘shish',
  edit: 'Tahrirlash',
  save: 'Saqlash',
  machineToken: 'Mashina tokeni',
  rotateToken: 'Tokenni yangilash',
  optionalEmployee: 'Xodim (ixtiyoriy)',
  optionalRoom: 'Xona (ixtiyoriy)',
  employeeDetailTitle: 'Kunlik hisobot',
  pickDate: 'Sana',
  officeTime: 'Ishxonada (turniket)',
  pcActive: 'PC faol',
  pcIdle: 'PC tushkun (ofisda)',
  pcBreak: 'Tanaffus (agent)',
  entriesList: 'Kirishlar',
  exitsList: 'Chiqishlar',
  breaksList: 'Dam olish / tushkunlik',
  snapshotOpen: 'Suratni ochish',
  analyticsTurnstile: 'Turniket (tanlangan davr)',
  analyticsEntries: 'Kirishlar',
  analyticsExits: 'Chiqishlar',
  attendanceTitle: 'Kungi yo‘qlama',
  attendanceDesc:
    'Turniket bo‘yicha ofisda bo‘lganlar (bo‘lim va lavozimi to‘ldirilgan xodimlar)',
  colPresent: 'Ofisda',
  colFirstEntry: 'Birinchi kirish',
  colLastExit: 'Oxirgi chiqish',
  bulkDelete: 'Tanlanganlarni o‘chirish',
  selectedN: 'ta tanlangan',
  cardIdLabel: 'Karta raqami',
  workStart: 'Ish boshlanishi',
  workEnd: 'Ish tugashi',
  computerDetailTitle: 'Kompyuter — kunlik faollik',
  activitySamples: 'Namunalar (so‘nggi)',
} as const
